<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>prySilvaMenendez_EjercicioSemana2</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>shop_icon-icons.com_51010.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="shop_icon-icons.com_51010.ico" />
  </ItemGroup>

</Project>